name: bunkr
description: "A simple, student-only alternative to Ezygo."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_secure_storage: ^9.0.0
  dio: ^5.7.0
  google_fonts: ^6.0.0
  intl: ^0.18.1
  flutter_svg: ^2.1.0
  badges: ^3.0.0
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/avatars/user.png
    - lib/assets/splash/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/icon.png"


flutter_native_splash:
  color: "#141414"                # Background color of splash screen
  image: lib/assets/splash/splash.png  # Path to splash image
  android: true
  ios: true
  web: false

  android_gravity: center        # Optional: Controls image alignment
  fullscreen: true               # Optional: Enables full screen mode

  android_12:
    color: "#141414"                     # Background color for Android 12
    image: assets/splash/splash.png      # Image shown in the Android 12 splash
